# .github/workflows/process-heat-data.yml
name: Processar Focos de Calor - Maranhão

on:
  schedule:
    # Executa a cada 60 minutos
    - cron: "0 * * * *"
  workflow_dispatch: # Permite execução manual
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/process-heat-data.yml'
      - 'scripts/process_focos_calor.py'
      - 'scripts/requirements.txt'

jobs:
  process-heat-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r scripts/requirements.txt  # CORRIGIDO: caminho correto
        
    - name: Setup Google Drive credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json
        
    - name: Process heat focus data
      run: python scripts/process_focos_calor.py  # CORRIGIDO: caminho correto
      
    - name: Cleanup credentials
      run: rm -f credentials.json
      
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Criar diretórios se não existirem
        mkdir -p logs data
        
        # Log de execução
        echo "$(date): Processo executado com sucesso" >> logs/execution_log.txt
        
        # Verificar se o arquivo JSON foi criado
        if [ -f "data/current_data_link.json" ]; then
          echo "✅ Arquivo data/current_data_link.json encontrado"
          cat data/current_data_link.json
        else
          echo "❌ Arquivo data/current_data_link.json NÃO encontrado"
          ls -la data/ || echo "Diretório data/ não existe"
        fi
        
        # Adicionar arquivos gerados
        git add logs/execution_log.txt
        git add data/ || echo "Erro ao adicionar diretório data/"
        
        # Verificar status
        git status
        
        # Verificar se há mudanças para commitar
        if git diff --staged --quiet; then
          echo "Nenhuma mudança para commitar"
        else
          git commit -m "🔥 Update: Processamento de focos $(date '+%Y-%m-%d %H:%M:%S')"
          git push || echo "Erro ao fazer push - repositório pode estar atualizado"
        fi
